# Makefile for Hotplugs
# Don't allow optimizations unless specified.
cflags-y	+= -O2

obj-$(CONFIG_INTELLI_PLUG)      += intelli_plug.o
obj-$(CONFIG_MSM_HOTPLUG)		+= msm_hotplug.o
obj-$(CONFIG_ALUCARD_HOTPLUG) += alucard_hotplug.o
obj-$(CONFIG_MAKO_HOTPLUG)		+= mako_hotplug.o
